apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: sampleweb
  labels:
    app: sampleweb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleweb
    spec:
      containers:
      - name: sampleweb-tomcat
        image: 192.168.56.1:5000/samplweb:27
        ports:
          - name: tomcat-port
            containerPort: 8080
        volumeMounts:
          - mountPath: /vol
            name: test-volume
      volumes:
      - name: test-volume
        hostPath:
            # directory location on host
            path: /container-overrides
            # this field is optional
            type: Directory

